# Generated by Django 6.1 on 2026-08-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_payment_provider_transaction_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider_transaction_id__isnull', False), ('status', 'successful')), models.Q(('status', 'successful'), _negated=True), _connector='OR'), name='successful_payment_has_provider_id'),
        ),
    ]
